name: favourty
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  styled_divider: ^1.0.5
  url_launcher: ^6.2.4
  iconify: ^0.0.1
  animated_path: ^0.0.2
  simple_gradient_text: ^1.3.0
  newton_particles: ^0.1.7
  tbib_splash_screen: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Bold.ttf

    - family: Rubik Moonrocks
      fonts:
        - asset: assets/fonts/RubikMoonrocks-Regular.ttf
 
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf
        - asset: assets/fonts/Tangerine-Bold.ttf
          weight: 700
        