name: Flutter Web Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Set up Flutter
        with:
          channel: stable  # Use the stable Flutter channel

      - name: Install dependencies
        run: flutter pub get  # Install Flutter dependencies

      - name: Build Flutter web
        run: flutter build web  # Build the Flutter web app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
          publish_dir: ./build/web  # Publish the `build/web` directory
